---
- name: include variables
  include_vars:
    file: ../../vars.yml

- name: elastic config remove
  become: yes
  file:
      path: "{{ elastic_yml }}"
      state: absent

- name: add empty elastic config
  become: yes
  file:
      path: "{{ elastic_yml }}"
      state: touch

- name: update elastic config
  become: yes
  blockinfile:
    path: "{{ elastic_yml }}"
    marker: ''
    block: |
       cluster.name: {{ elastic_cluster_name }}
       node.name: {{ inventory_hostname }}
       network.host: 0.0.0.0
       http.port: {{ elastic_port }}
       node.master: true
       node.data: false
       node.ingest: false
       discovery.seed_hosts: [{{ elastic_discovery_seeds }}]
       cluster.initial_master_nodes: [{{ elastic_master_nodes }}]
       path.data: /var/lib/elasticsearch
       path.logs: /var/log/elasticsearch

- name: start elasticsearch
  become: yes
  service:
    name: elasticsearch
    state: started
