---
- name: include variables
  include_vars:
    file: ../../vars.yml

- name: download logstash
  get_url:
    url: "{{ logstash_url }}{{logstash_version }}.rpm"
    dest: "{{ download }}"
  when: ansible_facts['distribution']=="Red Hat Enterprise Linux"

- name: install logstash
  become: yes
  yum:
    name: "{{ download }}/{{logstash_version }}.rpm"
    state: present
  when: ansible_facts['distribution']=="Red Hat Enterprise Linux"

- name: add empty logstash pipeline
  become: yes
  file:
    path: /etc/logstash/conf.d/main.conf
    state: touch

- name: update logstash pipeline
  become: yes
  blockinfile:
    path: /etc/logstash/conf.d/main.conf # elastic ip edit required
    marker: ""
    block: |
      input {
        beats {
          port => 5044
        }
      }
      output {
        elasticsearch { hosts => ["elk1:9200"]
        }
      }

- name: start logstash
  become: yes
  service:
    name: logstash
    state: started
