{
 "title": "Perf_EEA4_Resource",
 "time": { "from": "2023-10-11T12:59:56.000Z", "to": "2023-10-11T14:42:19.000Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"clusterName.keyword\"}"
   },
   {
    "name": "buildtime",
    "label": "Build",
    "query": "{\"find\": \"terms\", \"field\": \"buildTime.keyword\",\"query\": \"clusterName.keyword: $cluster\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"node.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildTime.keyword: $buildtime\" } "
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\": \"terms\", \"field\": \"namespace.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildTime.keyword: $buildtime AND node.keyword:$node\" } "
   },
   {
    "name": "microservice",
    "label": "µService",
    "query": "{\"find\": \"terms\", \"field\": \"microservice.keyword\",\"query\": \"clusterName: $cluster AND buildTime: $buildtime AND namespace: $namespace AND node.keyword:$node AND NOT microservice.keyword: eric-data-search-engine-curator\" } "
   },
   {
    "name": "pod",
    "label": "POD",
    "query": "{\"find\": \"terms\", \"field\": \"pod.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildTime.keyword: $buildtime AND namespace.keyword:$namespace AND microservice.keyword:$microservice AND node.keyword:$node\" } "
   },
   {
    "name": "container",
    "label": "Container",
    "query": "{\"find\": \"terms\", \"field\": \"container.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildTime.keyword: $buildtime AND namespace.keyword:$namespace AND pod.keyword:$pod  AND microservice.keyword:$microservice AND node.keyword:$node\" } "
   },
   {
    "name": "group",
    "label": "GroupBy",
    "query": "buildTime,node,namespace,microservice,pod,container"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m" },
   { "name": "min_memory_request", "label": "Min Memory Request [byte]", "query": "1" },
   { "name": "min_cpu_request", "label": "Min CPU Request [core]", "query": "0.00001" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overview (params,state,term reason - table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "µService",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "microservice.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "buildTime.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pod.keyword",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "container.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kube_pod_container_status_ready.keyword",
       "id": "19",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kube_pod_container_status_running.keyword",
       "id": "20",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kube_pod_container_status_waiting.keyword",
       "id": "21",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kube_pod_container_status_terminated.keyword",
       "id": "22",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "kube_pod_container_status_terminated_reason.keyword",
       "id": "23",
       "settings": {
        "min_doc_count": "1",
        "missing": "N/A",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "image.keyword",
       "id": "24",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "kube_pod_container_resource_limits_cpu_cores",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_requests_cpu_cores",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_limits_memory_bytes",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_requests_memory_bytes",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_status_restarts_total",
       "id": "15",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "NODE - Memory_usage over request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "node.keyword",
         "id": "10",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "clusterName.keyword",
         "id": "11",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "role.keyword",
         "id": "19",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "buildTime.keyword",
         "id": "29",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "kube_node_status_capacity_memory_bytes",
         "id": "14",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_node_status_allocatable_memory_bytes",
         "id": "15",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node",
       "timeField": "Timestamp"
      }
     ]
    },
    {
     "title": "${node} (ns: $namespace)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "repeat": "node",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "sum",
       "bucketAggs": [
        {
         "fake": true,
         "field": "namespace.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "container.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "node.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "Timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "container_memory_usage_bytes",
         "hide": true,
         "id": "1",
         "type": "sum"
        },
        {
         "field": "kube_pod_container_resource_requests_memory_bytes",
         "hide": true,
         "id": "6",
         "settings": { "missing": "0" },
         "type": "sum"
        },
        {
         "id": "7",
         "pipelineVariables": [
          { "name": "memory_usage", "pipelineAgg": "1" },
          { "name": "requests", "pipelineAgg": "6" }
         ],
         "settings": {
          "script": "if (params.memory_usage -  params.requests > 0 ){params.memory_usage -  params.requests}"
         },
         "type": "bucket_script"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node AND namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      },
      {
       "alias": "Request by ns",
       "bucketAggs": [
        {
         "field": "node.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "Timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_resource_requests_memory_bytes",
         "id": "1",
         "type": "sum"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node AND namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Max Usage / Requests and Limits ( table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Memory WorkingSet (this is what the OOM killer is watching for)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "microservice.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "buildTime.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pod.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "container.keyword",
       "id": "22",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "kube_pod_container_resource_requests_memory_bytes",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_limits_memory_bytes",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "min_memory_working_set",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "max_memory_working_set", "id": "19", "type": "max" },
      {
       "field": "max_memory_workingset_per_request",
       "id": "23",
       "type": "max"
      },
      {
       "field": "max_memory_workingset_per_limit",
       "id": "24",
       "type": "max"
      },
      { "field": "container_memory_failcnt", "id": "25", "type": "max" }
     ],
     "query": "kube_pod_container_resource_requests_memory_bytes: >=$min_memory_request AND clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage (this metric also includes cached items that can be evicted under memory pressure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "microservice.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "buildTime.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pod.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "container.keyword",
       "id": "22",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "kube_pod_container_resource_requests_memory_bytes",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_limits_memory_bytes",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "min_memory_usage",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "max_memory_usage", "id": "19", "type": "max" },
      { "field": "max_memory_usage_per_request", "id": "23", "type": "max" },
      { "field": "max_memory_usage_per_limit", "id": "24", "type": "max" },
      { "field": "container_memory_failcnt", "id": "25", "type": "max" }
     ],
     "query": "kube_pod_container_resource_requests_memory_bytes: >=$min_memory_request AND clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "CPU Max Usage / Requests and Limits ( table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "microservice.keyword",
         "id": "9",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "buildTime.keyword",
         "id": "10",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "node.keyword",
         "id": "11",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "namespace.keyword",
         "id": "17",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pod.keyword",
         "id": "18",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "container.keyword",
         "id": "22",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_resource_requests_cpu_cores",
         "id": "8",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_pod_container_resource_limits_cpu_cores",
         "id": "12",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "min_cpu_usage",
         "id": "13",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "max_cpu_usage",
         "id": "14",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        { "field": "max_cpu_usage_per_request", "id": "19", "type": "max" },
        { "field": "max_cpu_usage_per_limit", "id": "20", "type": "max" }
       ],
       "query": "kube_pod_container_resource_requests_cpu_cores: >=$min_cpu_request AND clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice",
       "timeField": "Timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Sum Requests and Limits group_by ${group} (graph)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "${group}.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "Timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_resource_requests_cpu_cores",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node AND namespace.keyword:$namespace AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      }
     ]
    },
    {
     "title": "CPU Limits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "${group}.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "Timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_resource_limits_cpu_cores",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node AND namespace.keyword:$namespace AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      }
     ]
    },
    {
     "title": "Memory Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "${group}.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "Timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_resource_requests_memory_bytes",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node AND namespace.keyword:$namespace AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "${group}.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "Timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_resource_limits_memory_bytes",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node AND namespace.keyword:$namespace AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      }
     ]
    }
   ]
  },
  { "title": "MEMORY group_by ${group}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Real Memory usage - Memory Working Set",
   "type": "graph",
   "description": "container_memory_working_set_bytes\n- Current working set in bytes.\n- This is what the OOM killer is watching for",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "${group}.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "container_memory_working_set_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Total Memory Usage (inclueding all memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "${group}.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "container_memory_usage_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "FailCnt - Memory usage hits limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "${group}.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "container_memory_failcnt",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "CPU group_by ${group}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "${group}.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "container_cpu_usage_seconds_total",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildTime.keyword:$buildtime AND node.keyword:$node namespace.keyword:$namespace AND pod.keyword:$pod AND container.keyword:$container AND microservice.keyword:$microservice AND pod_phase.keyword:Running",
       "timeField": "Timestamp"
      }
     ]
    }
   ]
  }
 ]
}