apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: eric-data-loader-eric-data-message-bus-kf-client-cert
  namespace: eric-eea-ns
spec:
  certificate:
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
    issuer:
      reference: eric-data-message-bus-kf-client-client-ca
    subject:
      cn: eric-data-loader
    subjectAlternativeName:
      populateKubernetesDns: false
    validity:
      overrideTtl: 15778800
  kubernetes:
    generatedSecretName: eric-data-loader-eric-data-message-bus-kf-client-cert
    secretType: tls
