apiVersion: v1
kind: Service
metadata:
  name: eric-ts-platform-data-document-database-pg-ext
  annotations:
    metallb.universe.tf/address-pool: pool0
    metallb.universe.tf/allow-shared-ip: rv-platform
spec:
  selector:
    app: eric-ts-platform-data-document-database-pg
    role: master  # Label to identify the writer Pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer