---
- name: modify privilege escalation rule for group 'wheel'
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: "%wheel\t\tALL=(ALL)\tNOPASSWD: ALL"
    backup: yes
    validate: "{{ visudo_prefix | default('') }}/sbin/visudo -qcf %s"

- name: add operator accounts
  user:
    name: "{{ signum }}"
    shell: /bin/bash
    groups: wheel
    append: yes
  loop: "{{ operators }}"
  loop_control:
    loop_var: signum
