---
- name: 'Retrieve eric-eea-external-ca secret'
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: eric-eea-external-ca
    namespace: '{{ eea_namespace }}'
  register: external_ca_secret

- name: 'Retrieve eric-lm-combined-server-external-server-certificate-secret secret'
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: eric-lm-combined-server-external-server-certificate-secret
    namespace: '{{ eea_namespace }}'
  register: lm_external_secret

#Create secret in Spotfire namespace
- name: "Remove old spotfire-server-tls secret from Spotfire namespace"
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: '{{ spotfire.namespace }}'
    name: spotfire-server-tls

- name: 'Create spotfire-server-tls secret'
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: spotfire-server-tls
        namespace: '{{ spotfire.namespace }}'
      data:
        'cacertbundle.pem': "{{ external_ca_secret.resources[0]['data']['ca.crt'] }}"
        'tls.crt': "{{ lm_external_secret.resources[0]['data']['tls.crt'] }}"
        'tls.key': "{{ lm_external_secret.resources[0]['data']['tls.key'] }}"
      type: Opaque