# PSQL DB is bootstrapped with spotfire user, so dashhboards should be deployed using same user
---
- name: 'Retrieve spotfire-database-secret secret'
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: spotfire-database-secret
    namespace: '{{ eea_namespace }}'
  register: sf_db_secret

- name: 'Decode and store the tss user and password from Secret'
  set_fact:
    sf_db_user_eea_ns: "{{ sf_db_secret.resources[0].data.user | b64decode }}"
    sf_db_pass_eea_ns: "{{ sf_db_secret.resources[0].data.pwd | b64decode }}"

- name: 'Validate that dashboard tables are deployed/will be deployed with {{ spotfire.db_user }} PSQL user'
  assert:
    that:
      - sf_db_user_eea_ns == spotfire.db_user
    fail_msg: >-
      The spotfire-database-secret in {{ eea_namespace }} contains wrong PSQL user: {{ sf_db_user_eea_ns }}!
      Meaning that dashboard tables are deployed with wrong user, but is should have been
      deployed with {{ spotfire.db_user }} user!
