---
- import_tasks:
    file: container_check.yml

# restart sf-server
# https://github.com/ansible-collections/kubernetes.core/issues/567
- name: Restart Spotfire server deployment
  kubernetes.core.k8s:
    state: patched
    kind: Deployment
    name: eric-ts-platform-spotfire-server
    namespace: "{{ spotfire.namespace }}"
    definition:
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ now(fmt='%Y-%m-%dT%H:%M:%SZ') }}"

- name: Sleep for 30 seconds
  wait_for:
    timeout: 30

- import_tasks:
    file: container_check.yml