{
 "title": "CI_EEA4_usage",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "\t{\"find\": \"terms\", \"field\": \"clusterName.keyword\"}"
   },
   {
    "name": "buildId",
    "label": "BuildId",
    "query": "{\"find\": \"terms\", \"field\": \"buildId.keyword\",\"query\": \"clusterName.keyword: $cluster\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"node.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildId.keyword: $buildId\" } "
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\": \"terms\", \"field\": \"namespace.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildId.keyword: $buildId AND node.keyword:$node\" } "
   },
   {
    "name": "microservice",
    "label": "uService",
    "query": "{\"find\": \"terms\", \"field\": \"microservice.keyword\",\"query\": \"clusterName: $cluster AND buildId: $buildId AND namespace: $namespace AND node.keyword:$node\" } "
   },
   {
    "name": "pod",
    "label": "POD",
    "query": "{\"find\": \"terms\", \"field\": \"pod.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildId.keyword: $buildId AND namespace.keyword:$namespace AND microservice.keyword:$microservice AND node.keyword:$node\" } "
   },
   {
    "name": "container",
    "label": "Container",
    "query": "{\"find\": \"terms\", \"field\": \"container_name.keyword\",\"query\": \"clusterName.keyword: $cluster AND buildId.keyword: $buildId AND namespace.keyword:$namespace AND pod.keyword:$pod  AND microservice.keyword:$microservice AND node.keyword:$node\" } "
   },
   { "name": "min_memory_request", "label": "Min Memory Request [byte]", "query": "1" },
   { "name": "min_cpu_request", "label": "Min CPU Request [core]", "query": "0.00001" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Node Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "node.keyword",
         "id": "10",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "clusterName.keyword",
         "id": "11",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "buildId.keyword",
         "id": "18",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "role.keyword",
         "id": "19",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "kernel_version.keyword",
         "id": "20",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "container_runtime_version.keyword",
         "id": "22",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "label_ccd_version.keyword",
         "id": "23",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "kubelet_version.keyword",
         "id": "12",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "kube_node_status_capacity_cpu_cores",
         "id": "8",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_node_status_allocatable_cpu_cores",
         "id": "13",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_node_status_capacity_memory_bytes",
         "id": "14",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_node_status_allocatable_memory_bytes",
         "id": "15",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_node_status_capacity_pods",
         "id": "16",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "kube_node_status_allocatable_pods",
         "id": "17",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildId.keyword:$buildId AND node.keyword:$node",
       "timeField": "Timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "microservice.keyword",
         "id": "9",
         "settings": {
          "min_doc_count": 1,
          "missing": "MISSING",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "buildId.keyword",
         "id": "10",
         "settings": {
          "min_doc_count": 1,
          "missing": "MISSING",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "namespace.keyword",
         "id": "11",
         "settings": {
          "min_doc_count": 1,
          "missing": "MISSING",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pod.keyword",
         "id": "17",
         "settings": {
          "min_doc_count": 1,
          "missing": "MISSING",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "container_name.keyword",
         "id": "18",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "kube_pod_container_status_ready",
         "id": "23",
         "type": "avg"
        },
        {
         "field": "kube_pod_container_status_running",
         "id": "24",
         "type": "avg"
        },
        {
         "field": "kube_pod_container_status_terminated",
         "id": "25",
         "type": "avg"
        },
        {
         "field": "kube_pod_container_status_waiting",
         "id": "26",
         "type": "avg"
        },
        {
         "field": "kube_pod_container_status_restarts_total",
         "id": "27",
         "type": "max"
        }
       ],
       "query": "clusterName.keyword:$cluster AND buildId.keyword:$buildId AND namespace.keyword:$namespace AND pod.keyword:$pod AND container_name.keyword:$container AND microservice.keyword:$microservice",
       "timeField": "Timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Resource Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Memory WorkingSet (this is what the OOM killer is watching for)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "microservice.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "buildId.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pod.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "container_name.keyword",
       "id": "22",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "kube_pod_container_resource_requests_memory_bytes",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_limits_memory_bytes",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "min_memory_working_set",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "max_memory_working_set", "id": "19", "type": "max" },
      {
       "field": "max_memory_workingset_per_request",
       "id": "23",
       "type": "max"
      },
      {
       "field": "max_memory_workingset_per_limit",
       "id": "24",
       "type": "max"
      },
      { "field": "container_memory_failcnt", "id": "25", "type": "max" }
     ],
     "query": "kube_pod_container_resource_requests_memory_bytes: >=$min_memory_request AND clusterName.keyword:$cluster AND buildId.keyword:$buildId AND namespace.keyword:$namespace AND pod.keyword:$pod AND container_name.keyword:$container AND microservice.keyword:$microservice",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage (this metric also includes cached items that can be evicted under memory pressure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "microservice.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "buildId.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pod.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "container_name.keyword",
       "id": "22",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "kube_pod_container_resource_requests_memory_bytes",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_limits_memory_bytes",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "min_memory_usage",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "max_memory_usage", "id": "19", "type": "max" },
      { "field": "max_memory_usage_per_request", "id": "23", "type": "max" },
      { "field": "max_memory_usage_per_limit", "id": "24", "type": "max" },
      { "field": "container_memory_failcnt", "id": "25", "type": "max" }
     ],
     "query": "kube_pod_container_resource_requests_memory_bytes: >=$min_memory_request AND clusterName.keyword:$cluster AND buildId.keyword:$buildId AND namespace.keyword:$namespace AND pod.keyword:$pod AND container_name.keyword:$container AND microservice.keyword:$microservice",
     "timeField": "Timestamp"
    }
   ]
  },
  { "title": "Resource CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "microservice.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "buildId.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "namespace.keyword",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pod.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "container_name.keyword",
       "id": "22",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "kube_pod_container_resource_requests_cpu_cores",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "kube_pod_container_resource_limits_cpu_cores",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "min_cpu_usage",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "max_cpu_usage",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "max_cpu_usage_per_request", "id": "19", "type": "max" },
      { "field": "max_cpu_usage_per_limit", "id": "20", "type": "max" }
     ],
     "query": "kube_pod_container_resource_requests_cpu_cores: >=$min_cpu_request AND clusterName.keyword:$cluster AND buildId.keyword:$buildId AND namespace.keyword:$namespace AND pod.keyword:$pod AND container_name.keyword:$container AND microservice.keyword:$microservice",
     "timeField": "Timestamp"
    }
   ]
  }
 ]
}